server:
  port: 8080
  servlet:
    context-path: /dbmanager
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1/dbmanager?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
